"""empty message

Revision ID: c9233c660b0f
Revises: 3b6ae99f009f
Create Date: 2025-05-04 20:06:53.636185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9233c660b0f'
down_revision = '3b6ae99f009f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_Url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('image_Url')

    # ### end Alembic commands ###
