"""empty message

Revision ID: f9d029cfd6dd
Revises: c9233c660b0f
Create Date: 2025-05-04 21:10:20.779231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d029cfd6dd'
down_revision = 'c9233c660b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opinions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating_cliente', schema=None) as batch_op:
        batch_op.drop_column('opinions')

    # ### end Alembic commands ###
